### ISSUE TITLE
Fail to built

### ISSUE THREAD

**Issue by Timo-AL** [torch-points3d/torch-points-kernels#101]
OS：windows11 22H2
C++ Compiler： MSVC2022
Python：3.8
CudatoolKit：release 11.8, V11.8.89
pytorch：2.0.1

I am try to install torch points kernels 0.6.10 via pip
then I got these

```
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-38
      creating build\lib.win32-cpython-38\torch_points_kernels
      copying torch_points_kernels\chamfer_dist.py -> build\lib.win32-cpython-38\torch_points_kernels
      copying torch_points_kernels\cluster.py -> build\lib.win32-cpython-38\torch_points_kernels
      copying torch_points_kernels\cubic_feature_sampling.py -> build\lib.win32-cpython-38\torch_points_kernels
      copying torch_points_kernels\gridding.py -> build\lib.win32-cpython-38\torch_points_kernels
      copying torch_points_kernels\knn.py -> build\lib.win32-cpython-38\torch_points_kernels
      copying torch_points_kernels\metrics.py -> build\lib.win32-cpython-38\torch_points_kernels
      copying torch_points_kernels\torchpoints.py -> build\lib.win32-cpython-38\torch_points_kernels
      copying torch_points_kernels\__init__.py -> build\lib.win32-cpython-38\torch_points_kernels
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ASUS\AppData\Local\Temp\pip-install-9vtektg3\torch-points-kernels_43eb08ed507e4a51ac0e9e548f108dbd\setup.py", line 76, in <module>
          setup(
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\torch\utils\cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 52, in parse
          return Version(version)
        File "C:\Users\ASUS\miniconda3\envs\p3d\lib\site-packages\pkg_resources\_vendor\packaging\version.py", line 195, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]
```

**Comment by Timo-AL** [comment]
By the way, torch points kernels 0.7.0 can install successfully. and 0.6.6 to 0.6.10 meet this problem.

**Comment by LegionHXF** [comment]
> 顺便问一下，torch points kernels 0.7.0可以安装成功，0.6.6到0.6.10都出现这个问题， 我的系统语言是简体中文，GBK文本编码能解决这个问题吗？

你好，我目前在liunx上并不能成功安装他，我不知道是否是环境出现了问题？您可以告诉我你的环境是什么吗？pytorch+cuda
